# Generated by Django 3.1.4 on 2020-12-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdv', '0002_auto_20201217_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(choices=[('dupla adulto', 'DUPLA ADULTO'), ('hepatite b', 'HEPATITE B'), ('sar/cax/rub', 'SAR/CAX/RUB'), ('febre amarela', 'FEBRE AMARELA')], default='dupla adulto', max_length=15)),
                ('lote', models.CharField(max_length=10)),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('profissional', models.CharField(max_length=250)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdv.paciente')),
            ],
        ),
    ]
