# Generated by Django 3.1.4 on 2020-12-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv', '0003_carteira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='vacina',
            field=models.CharField(choices=[('DUPLA ADULTO', 'DUPLA ADULTO'), ('HEPATITE B', 'HEPATITE B'), ('SAR/CAX/RUB', 'SAR/CAX/RUB'), ('FEBRE AMARELA', 'FEBRE AMARELA')], default='DUPLA ADULTO', max_length=15),
        ),
    ]
