# Generated by Django 3.1.4 on 2020-12-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdv', '0005_carteira_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(choices=[('DUPLA ADULTO', 'DUPLA ADULTO'), ('HEPATITE B', 'HEPATITE B'), ('SAR/CAX/RUB', 'SAR/CAX/RUB'), ('FEBRE AMARELA', 'FEBRE AMARELA')], default='DUPLA ADULTO', max_length=15)),
                ('data', models.DateField()),
                ('lote', models.CharField(max_length=10)),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('profissional', models.CharField(max_length=250)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdv.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Carteira',
        ),
    ]
