# Generated by Django 3.1.4 on 2020-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv', '0006_auto_20201217_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='local_disponivel',
            field=models.CharField(choices=[('PSF-CENTRO', 'PSF-CENTRO'), ('PSF-NORTE', 'PSF-NORTE'), ('PSF-SUL', 'PSF-SUL'), ('PSF-OESTE', 'PSF-OESTE')], default='PSF-CENTRO', max_length=15),
        ),
    ]
